name = "MondrianForests"
uuid = "3e47f106-5d41-4e23-9040-914dff44c15a"
authors = ["William G Underwood <42812654+WGUNDERWOOD@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
