name = "MondrianForests"
uuid = "3e47f106-5d41-4e23-9040-914dff44c15a"
authors = ["William G Underwood <42812654+WGUNDERWOOD@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Aqua = "0.8"
Distributions = "0.25"
JuliaFormatter = "1"
Random = "1"
Suppressor = "0.2"
Test = "1"
julia = "1"
