name = "MondrianForests"
uuid = "3e47f106-5d41-4e23-9040-914dff44c15a"
authors = ["William G Underwood <42812654+WGUNDERWOOD@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
ProfileSVG = "132c30aa-f267-4189-9183-c8a63c7e05e6"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
